name: Check DB and Create Jira Fix Version

on:
  schedule:
    - cron: '0 * * * *'  # Every 1 hour
  workflow_dispatch:

jobs:
  check-and-create:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run Script
      env:
        
      run: python script.py
 
